
variable "apps" {
  type    = string
  default = "false"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "iso_checksum" {
  type    = string
  default = "436AF9C7BD0330B1860A53E58407778AAE804FB22FF4816FF4E669B23E3FEDFC"
}

variable "iso_url" {
  type    = string
  default = "http://localhost:8080/SW_DVD9_Win_Server_STD_CORE_2019_1809.13_64Bit_English_DC_STD_MLF_X22-57176.ISO"
}

variable "switch_name" {
  type    = string
  default = "Internal with internet"
}

variable "winrm_password" {
  type    = string
  default = "vagrant"
}

variable "winrm_username" {
  type    = string
  default = "vagrant"
}

source "hyperv-iso" "autogenerated_1" {
  communicator     = "winrm"
  cpus             = "2"
  disk_size        = 61440
  floppy_files     = ["windows10/English/Autounattend.xml", "Scripts/firstboot.ps1"]
  headless         = "${var.headless}"
  iso_checksum     = "${var.iso_checksum}"
  iso_url          = "${var.iso_url}"
  memory           = 4096
  shutdown_command = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  switch_name      = "${var.switch_name}"
  vm_name          = "20H2 VagrantBox"
  winrm_password   = "${var.winrm_password}"
  winrm_timeout    = "3h"
  winrm_username   = "${var.winrm_username}"
}

build {
  sources = ["source.hyperv-iso.autogenerated_1"]

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/Winupdate.ps1"
    valid_exit_codes  = [0]
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/Winupdate.ps1"
    valid_exit_codes  = [0]
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/Remove-BuildinApps.ps1"
    valid_exit_codes  = [0]
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/Winupdate.ps1"
    valid_exit_codes  = [0]
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

  provisioner "file" {
    destination = "C:\\startmenu.xml"
    source      = "Windows10/startmenu.xml"
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/provision.ps1"
    valid_exit_codes  = [0]
  }

  provisioner "powershell" {
    elevated_password = "vagrant"
    elevated_user     = "vagrant"
    script            = "Scripts/Cleanup.ps1"
    valid_exit_codes  = [0]
  }

}
